name: Python application test with GitHub Actions

# Do it when pushing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Runner environment

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.11
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test

    
